CREATE DATABASE yeticave
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

USE yeticave;

CREATE TABLE categories (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL
);

CREATE TABLE lots (
id INT AUTO_INCREMENT PRIMARY KEY,
date_create DATETIME  NOT NULL,
name VARCHAR(255) NOT NULL,
description TEXT NOT NULL,
image VARCHAR(255) NOT NULL,
start_price DECIMAL(18) NOT NULL,
date_end DATETIME NOT NULL,
step_price DECIMAL(18) NOT NULL,
author_id INT NOT NULL,
winner_id INT,
category_id INT NOT NULL
);

CREATE TABLE bets (
id INT AUTO_INCREMENT PRIMARY KEY,
created_at DATETIME NOT NULL,
amount DECIMAL(18) NOT NULL,
user_id INT NOT NULL,
lot_id INT NOT NULL
);

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
date_registr DATETIME NOT NULL,
email VARCHAR(255) NOT NULL,
name VARCHAR(255) NOT NULL,
pass VARCHAR(255) NOT NULL,
image VARCHAR(255),
phone VARCHAR(255) NOT NULL,
);

CREATE UNIQUE INDEX cat_name ON categories(name); -- создаю индексы
CREATE INDEX l_name ON lots(name);
CREATE UNIQUE INDEX u_email ON users(email);
CREATE UNIQUE INDEX u_name ON users(name);
CREATE UNIQUE INDEX u_phone ON users(phone);

ALTER TABLE lots ADD CONSTRAINT FOREIGN KEY (category_id)  REFERENCES categories (Id) ON DELETE CASCADE ON UPDATE CASCADE; -- назначаю внешние ключи
ALTER TABLE lots ADD CONSTRAINT FOREIGN KEY (author_id)  REFERENCES users (Id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE lots ADD CONSTRAINT FOREIGN KEY (winner_id)  REFERENCES users (Id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE bets ADD CONSTRAINT FOREIGN KEY (user_id)  REFERENCES users (Id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE bets ADD CONSTRAINT FOREIGN KEY (lot_id)  REFERENCES lots (Id) ON DELETE CASCADE ON UPDATE CASCADE;